"""
core/avi_import.py
Strict import contract for discovery payloads.

Import accepts only normalized discovery JSON generated by the analyzer flow.
Heuristic extraction from raw Avi exports is intentionally unsupported.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from core.events import EventBus, Phase
from collectors.virtual_service import VirtualServiceCollector
from collectors.pool import PoolCollector, HealthMonitorCollector
from collectors.ssl import SSLProfileCollector, SSLCertificateCollector
from collectors.profiles import (
    ApplicationProfileCollector,
    NetworkProfileCollector,
    PersistenceProfileCollector,
)
from collectors.datascript import DataScriptCollector
from collectors.system import (
    ServiceEngineGroupCollector,
    GSLBCollector,
    GSLBGlobalCollector,
    GSLBGeoDbCollector,
    AlertConfigCollector,
    CloudContextCollector,
    TenantContextCollector,
    VrfContextCollector,
    IpAddrGroupCollector,
    IpamDnsProviderCollector,
    NetworkContextCollector,
)


DISCOVERY_KEYS = [
    "_meta",
    "virtual_services",
    "vs_vips",
    "pools",
    "pool_groups",
    "health_monitors",
    "ssl_certificates",
    "ssl_profiles",
    "application_profiles",
    "network_profiles",
    "persistence_profiles",
    "http_policy_sets",
    "dns_policies",
    "waf_policies",
    "auth_profiles",
    "datascripts",
    "se_groups",
    "gslb_global",
    "gslb_services",
    "gslb_geo_db",
    "alert_configs",
    "connections",
    "clouds",
    "tenants",
    "vrf_contexts",
    "ip_addr_groups",
    "ipam_dns_providers",
    "networks",
]

RAW_TO_DISCOVERY_MAP = {
    "VirtualService": "virtual_services",
    "VsVip": "vs_vips",
    "Pool": "pools",
    "PoolGroup": "pool_groups",
    "HealthMonitor": "health_monitors",
    "SSLKeyAndCertificate": "ssl_certificates",
    "SSLProfile": "ssl_profiles",
    "ApplicationProfile": "application_profiles",
    "NetworkProfile": "network_profiles",
    "ApplicationPersistenceProfile": "persistence_profiles",
    "HTTPPolicySet": "http_policy_sets",
    "DnsPolicy": "dns_policies",
    "WafPolicy": "waf_policies",
    "AuthProfile": "auth_profiles",
    "VSDataScriptSet": "datascripts",
    "ServiceEngineGroup": "se_groups",
    "Gslb": "gslb_global",
    "GslbService": "gslb_services",
    "GslbGeoDbProfile": "gslb_geo_db",
    "AlertConfig": "alert_configs",
    "connections": "connections",
    "Cloud": "clouds",
    "Tenant": "tenants",
    "VrfContext": "vrf_contexts",
    "IpAddrGroup": "ip_addr_groups",
    "IpamDnsProviderProfile": "ipam_dns_providers",
    "Network": "networks",
}



def is_raw_avi_export(payload: Any) -> bool:
    if not isinstance(payload, dict):
        return False
    return "VirtualService" in payload or "META" in payload or "AviConfig" in payload


def normalize_raw_avi_export(payload: dict[str, Any], env_name: str, source_file: str = "") -> dict[str, Any]:
    """Normalize raw AVI export JSON into strict discovery shape."""
    # Unwrap AviConfig if present
    if "AviConfig" in payload and isinstance(payload["AviConfig"], dict):
        payload = {**payload["AviConfig"], "META": payload.get("META", {})}
    
    meta = payload.get("META", {}) if isinstance(payload.get("META"), dict) else {}
    discovery: dict[str, Any] = {
        "_meta": {
            "tool_version": "imported",
            "tenant": meta.get("use_tenant", env_name),
            "source": "raw_avi_export",
            "imported_from": source_file or "ui_import",
            "avi_controller": meta.get("controller", ""),
        }
    }
    for raw_key, normalized_key in RAW_TO_DISCOVERY_MAP.items():
        val = payload.get(raw_key, [])
        discovery[normalized_key] = val if isinstance(val, list) else []
    for key in DISCOVERY_KEYS:
        if key not in discovery:
            discovery[key] = {} if key == "_meta" else []
    return discovery


def import_avi_json(input_path: str | Path, env_name: str, bus: EventBus) -> dict:
    """
    Import a normalized discovery JSON file using strict validation.
    """
    input_file = Path(input_path)
    with input_file.open("r", encoding="utf-8") as fh:
        payload = json.load(fh)

    return import_discovery_payload(payload, env_name=env_name, bus=bus, source_file=input_file)


def import_discovery_payload(
    payload: dict[str, Any],
    env_name: str,
    bus: EventBus,
    source_file: str | Path = "",
) -> dict:
    """
    Import pre-normalized discovery payload using strict schema checks.
    """
    source_name = str(source_file) if source_file else "in-memory payload"
    _validate_discovery_payload(payload)
    discovery = dict(payload)
    discovery.setdefault("_meta", {})
    discovery["_meta"].setdefault("tool_version", "imported")
    discovery["_meta"].setdefault("tenant", env_name)
    discovery["_meta"].setdefault("source", "normalized_discovery_json")
    discovery["_meta"].setdefault("imported_from", source_name)

    _enrich_imported_discovery(discovery, bus)
    _log_import_summary(discovery, source_name, bus)
    return discovery


def _validate_discovery_payload(payload: Any) -> None:
    if not isinstance(payload, dict):
        raise ValueError("Invalid discovery payload: expected JSON object at root.")

    if "VirtualService" in payload or "VirtualServices" in payload:
        raise ValueError(
            "Raw Avi export detected. This importer accepts normalized discovery JSON only. "
            "Normalize the export in the analyzer, then import as discovery JSON."
        )

    missing = [key for key in DISCOVERY_KEYS if key not in payload]
    if missing:
        raise ValueError(
            "Invalid discovery payload: missing required keys: "
            + ", ".join(missing)
        )

    if not isinstance(payload["_meta"], dict):
        actual = type(payload["_meta"]).__name__
        raise ValueError(
            f"Invalid discovery payload: key '_meta' must be object, got {actual}."
        )

    wrong_types = []
    for key in DISCOVERY_KEYS:
        if key == "_meta":
            continue
        value = payload.get(key)
        if not isinstance(value, list):
            wrong_types.append(f"{key} (expected array, got {type(value).__name__})")
    if wrong_types:
        raise ValueError(
            "Invalid discovery payload: wrong key types: " + "; ".join(wrong_types)
        )


def _enrich_imported_discovery(discovery: dict, bus: EventBus) -> None:
    enrichers = [
        ("virtual_services", VirtualServiceCollector),
        ("pools", PoolCollector),
        ("health_monitors", HealthMonitorCollector),
        ("ssl_profiles", SSLProfileCollector),
        ("ssl_certificates", SSLCertificateCollector),
        ("application_profiles", ApplicationProfileCollector),
        ("network_profiles", NetworkProfileCollector),
        ("persistence_profiles", PersistenceProfileCollector),
        ("datascripts", DataScriptCollector),
        ("se_groups", ServiceEngineGroupCollector),
        ("gslb_services", GSLBCollector),
        ("gslb_global", GSLBGlobalCollector),
        ("gslb_geo_db", GSLBGeoDbCollector),
        ("alert_configs", AlertConfigCollector),
        ("clouds", CloudContextCollector),
        ("tenants", TenantContextCollector),
        ("vrf_contexts", VrfContextCollector),
        ("ip_addr_groups", IpAddrGroupCollector),
        ("ipam_dns_providers", IpamDnsProviderCollector),
        ("networks", NetworkContextCollector),
    ]

    for key, collector_cls in enrichers:
        items = discovery.get(key, [])
        if not items:
            continue
        collector = collector_cls(None, bus)
        discovery[key] = collector._post_process(items)


def _log_import_summary(discovery: dict, source_name: str, bus: EventBus) -> None:
    counts = {
        key: len(value)
        for key, value in discovery.items()
        if key != "_meta" and isinstance(value, list) and value
    }
    bus.info(
        Phase.COLLECT,
        f"Imported normalized discovery JSON from '{source_name}'",
        detail={"counts": counts},
    )
