#!/usr/bin/env bash
# scripts/dns-cutover.sh
# ─────────────────────────────────────────────────────────────────────────────
# AVI → FortiADC DNS Cutover Script
# Switches VIP DNS A-records from AVI to FortiADC via Infoblox WAPI.
#
# USAGE:
#   bash scripts/dns-cutover.sh --env <env> --dry-run    # simulate only
#   bash scripts/dns-cutover.sh --env <env> --execute    # real cutover
#
# REQUIRED ENV VARS (or prompted interactively):
#   INFOBLOX_HOST     — Infoblox grid master FQDN or IP
#   INFOBLOX_USER     — Infoblox API username
#   INFOBLOX_PASS     — Infoblox API password
#   INFOBLOX_VIEW     — DNS view (default: default)
#   WAPI_VERSION      — Infoblox WAPI version (default: 2.10)
#
# REQUIRED FILES (generated by the migration tool):
#   discovery/<env>.json        — contains AVI VIP list
#   fortiadc/<env>-config.json  — contains FortiADC VIP list
#   state/<env>-ledger.json     — checked for deploy completion
#
# SAFETY:
#   - Always run --dry-run first (wizard enforces this)
#   - TTLs are lowered to 60s before record changes
#   - All changes logged to logs/<env>-dns-cutover.log
#   - Original records backed up to state/<env>-dns-backup.json
#   - Script is idempotent — safe to re-run if interrupted
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

ok()   { echo -e "${GREEN}[OK]${NC}    $*"; }
info() { echo -e "${CYAN}[INFO]${NC}  $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail() { echo -e "${RED}[FAIL]${NC}  $*"; }
step() { echo -e "\n${BOLD}─── $* ───${NC}"; }

# ── Argument parsing ──────────────────────────────────────────────────────────
ENV=""
DRY_RUN=true
LOG_DIR="logs"
STATE_DIR="state"

usage() {
    echo "Usage: $0 --env <environment> [--dry-run | --execute]"
    echo "       --dry-run   Simulate changes only (default)"
    echo "       --execute   Apply real DNS changes"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)      ENV="${2:?--env requires a value}"; shift 2 ;;
        --dry-run)  DRY_RUN=true;  shift ;;
        --execute)  DRY_RUN=false; shift ;;
        --help|-h)  usage ;;
        *) echo "Unknown argument: $1"; usage ;;
    esac
done

[[ -z "$ENV" ]] && { fail "--env is required"; usage; }

# ── Setup ─────────────────────────────────────────────────────────────────────
mkdir -p "$LOG_DIR" "$STATE_DIR"
LOG_FILE="$LOG_DIR/${ENV}-dns-cutover.log"
BACKUP_FILE="$STATE_DIR/${ENV}-dns-backup.json"
DISCOVERY="discovery/${ENV}.json"
FORTIADC_CFG="fortiadc/${ENV}-config.json"

MODE=$( $DRY_RUN && echo "DRY-RUN" || echo "EXECUTE" )
exec > >(tee -a "$LOG_FILE") 2>&1

echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  AVI → FortiADC DNS Cutover"
echo "  Environment : $ENV"
echo "  Mode        : $MODE"
echo "  Started     : $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "  Log         : $LOG_FILE"
echo "══════════════════════════════════════════════════════════════"

# ── Pre-flight checks ─────────────────────────────────────────────────────────
step "Pre-flight checks"

# Check required files
[[ -f "$DISCOVERY"    ]] || { fail "Discovery file not found: $DISCOVERY — run Step 1 (Discover) first"; exit 1; }
[[ -f "$FORTIADC_CFG" ]] || { fail "FortiADC config not found: $FORTIADC_CFG — run Step 3 (Transform) first"; exit 1; }

ok "Discovery file found: $DISCOVERY"
ok "FortiADC config found: $FORTIADC_CFG"

# Check deploy is complete
LEDGER="$STATE_DIR/${ENV}-ledger.json"
if [[ -f "$LEDGER" ]]; then
    DEPLOY_STATUS=$(python3 -c "
import json, sys
d = json.load(open('$LEDGER'))
print(d.get('phases', {}).get('deploy', {}).get('status', 'pending'))
" 2>/dev/null || echo "unknown")
    if [[ "$DEPLOY_STATUS" != "done" ]]; then
        fail "Deploy phase status: $DEPLOY_STATUS — FortiADC must be deployed before DNS cutover."
        exit 1
    fi
    ok "FortiADC deploy confirmed complete in state ledger"
else
    warn "State ledger not found — cannot verify deploy completion. Proceeding anyway."
fi

# Check python3
command -v python3 >/dev/null 2>&1 || { fail "python3 required but not found"; exit 1; }
ok "python3 available"

# ── Gather Infoblox credentials ───────────────────────────────────────────────
step "Infoblox credentials"

INFOBLOX_HOST="${INFOBLOX_HOST:-}"
INFOBLOX_USER="${INFOBLOX_USER:-}"
INFOBLOX_PASS="${INFOBLOX_PASS:-}"
INFOBLOX_VIEW="${INFOBLOX_VIEW:-default}"
WAPI_VERSION="${WAPI_VERSION:-2.10}"

if [[ -z "$INFOBLOX_HOST" ]]; then
    read -r -p "  Infoblox host (FQDN or IP): " INFOBLOX_HOST
fi
if [[ -z "$INFOBLOX_USER" ]]; then
    read -r -p "  Infoblox username: " INFOBLOX_USER
fi
if [[ -z "$INFOBLOX_PASS" ]]; then
    read -r -s -p "  Infoblox password: " INFOBLOX_PASS
    echo
fi

WAPI_BASE="https://${INFOBLOX_HOST}/wapi/v${WAPI_VERSION}"
info "WAPI endpoint: $WAPI_BASE"
info "DNS view: $INFOBLOX_VIEW"

# Test Infoblox connectivity
info "Testing Infoblox connection..."
IB_HTTP=$(curl -sk -o /dev/null -w "%{http_code}" \
    -u "${INFOBLOX_USER}:${INFOBLOX_PASS}" \
    "${WAPI_BASE}/grid" || echo "000")

case "$IB_HTTP" in
    200) ok "Infoblox connection successful" ;;
    401) fail "Infoblox: authentication failed — check username/password"; exit 1 ;;
    000) fail "Infoblox: unreachable — check hostname/network"; exit 1 ;;
    *)   fail "Infoblox: unexpected response HTTP $IB_HTTP"; exit 1 ;;
esac

# ── Build VIP mapping ─────────────────────────────────────────────────────────
step "Building VIP mapping: AVI VIPs → FortiADC VIPs"

VIP_MAP=$(python3 - <<'PYEOF'
import json, sys

discovery = json.load(open("$DISCOVERY"))
fortiadc   = json.load(open("$FORTIADC_CFG"))

# AVI VIPs from discovery
avi_vips = {}
for vs in discovery.get("virtual_services", []):
    for vip in vs.get("_vips", []):
        avi_vips[vs["name"]] = vip

# FortiADC VIPs from config
forti_vips = {}
for vs in fortiadc.get("virtual_servers", []):
    name = vs.get("name", "")
    ip   = vs.get("ip", "")
    if name and ip:
        forti_vips[name] = ip

# Build mapping: AVI VIP → FortiADC VIP (by VS name match)
mapping = []
for vs_name, avi_vip in avi_vips.items():
    forti_vip = forti_vips.get(vs_name, "")
    if forti_vip and forti_vip != avi_vip:
        mapping.append({
            "vs_name": vs_name,
            "avi_vip": avi_vip,
            "forti_vip": forti_vip
        })
    elif not forti_vip:
        mapping.append({
            "vs_name": vs_name,
            "avi_vip": avi_vip,
            "forti_vip": None,
            "warning": "No FortiADC VS found for this AVI VS"
        })

print(json.dumps(mapping, indent=2))
PYEOF
)

VIP_COUNT=$(echo "$VIP_MAP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(len([v for v in d if v.get('forti_vip')]))")
WARN_COUNT=$(echo "$VIP_MAP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(len([v for v in d if v.get('warning')]))")

info "VIPs to switch: $VIP_COUNT"
[[ "$WARN_COUNT" -gt 0 ]] && warn "VIPs with no FortiADC match: $WARN_COUNT (will be skipped)"

# ── Discover DNS records for AVI VIPs ────────────────────────────────────────
step "Discovering Infoblox A-records for AVI VIPs"

# Extract unique AVI VIPs
AVI_VIPS=$(echo "$VIP_MAP" | python3 -c "
import json, sys
d = json.load(sys.stdin)
for item in d:
    if item.get('forti_vip'):
        print(item['avi_vip'])
")

DNS_RECORDS="[]"
for VIP in $AVI_VIPS; do
    RECORDS=$(curl -sk -u "${INFOBLOX_USER}:${INFOBLOX_PASS}" \
        "${WAPI_BASE}/record:a?ipv4addr=${VIP}&view=${INFOBLOX_VIEW}&_return_fields=name,ipv4addr,ttl,_ref" \
        2>/dev/null || echo "[]")
    DNS_RECORDS=$(python3 -c "
import json, sys
existing = json.loads('$DNS_RECORDS'.replace(\"'\", '\"') if '$DNS_RECORDS' != '[]' else '[]')
new = json.loads('''$RECORDS''')
print(json.dumps(existing + new))
" 2>/dev/null || echo "$DNS_RECORDS")
done

RECORD_COUNT=$(echo "$DNS_RECORDS" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
info "Found $RECORD_COUNT DNS A-record(s) pointing to AVI VIPs"

if [[ "$RECORD_COUNT" -eq 0 ]]; then
    warn "No DNS A-records found for AVI VIPs. Nothing to update."
    warn "This may indicate DNS records use a different view, or VIPs don't match."
    $DRY_RUN || { info "Exiting — nothing to do."; exit 0; }
fi

# ── Backup DNS records ────────────────────────────────────────────────────────
step "Backing up current DNS records"

BACKUP_DATA=$(python3 -c "
import json
from datetime import datetime, timezone

backup = {
    'env': '$ENV',
    'backed_up_at': datetime.now(timezone.utc).isoformat(),
    'mode': '$MODE',
    'vip_map': $VIP_MAP,
    'dns_records': $DNS_RECORDS,
}
print(json.dumps(backup, indent=2))
")

if $DRY_RUN; then
    info "[DRY-RUN] Would write backup to: $BACKUP_FILE"
else
    echo "$BACKUP_DATA" > "$BACKUP_FILE"
    ok "DNS records backed up to: $BACKUP_FILE"
fi

# ── Phase 1: Lower TTLs ───────────────────────────────────────────────────────
step "Phase 1: Lower DNS TTLs to 60 seconds"

info "Lowering TTLs allows DNS propagation in 60s after record change."
info "In a real deployment, TTLs should be lowered 24h before the cutover window."

echo "$DNS_RECORDS" | python3 -c "
import json, sys
records = json.load(sys.stdin)
for r in records:
    old_ttl = r.get('ttl', 300)
    print(f\"  {r['name']:<50} TTL: {old_ttl}s → 60s\")
"

if $DRY_RUN; then
    info "[DRY-RUN] Would lower TTLs on $RECORD_COUNT record(s)"
else
    echo "$DNS_RECORDS" | python3 - <<'PYEOF'
import json, sys, subprocess, os

records  = json.load(sys.stdin)
host     = os.environ.get("INFOBLOX_HOST", "")
user     = os.environ.get("INFOBLOX_USER", "")
password = os.environ.get("INFOBLOX_PASS", "")
view     = os.environ.get("INFOBLOX_VIEW", "default")
wapi     = f"https://{host}/wapi/v2.10"

for r in records:
    ref = r.get("_ref", "")
    if not ref:
        continue
    result = subprocess.run(
        ["curl", "-sk", "-X", "PUT",
         "-u", f"{user}:{password}",
         "-H", "Content-Type: application/json",
         "-d", '{"ttl": 60, "use_ttl": true}',
         f"{wapi}/{ref}"],
        capture_output=True, text=True
    )
    if result.returncode == 0 and result.stdout.strip().startswith('"'):
        print(f"  OK: TTL lowered — {r['name']}")
    else:
        print(f"  WARN: TTL update failed — {r['name']}: {result.stderr[:100]}")
PYEOF

    info "Waiting 65 seconds for TTL propagation..."
    sleep 65
fi

ok "Phase 1 complete: TTLs lowered"

# ── Phase 2: Update A-records to FortiADC VIPs ───────────────────────────────
step "Phase 2: Update A-records to point to FortiADC VIPs"

CHANGE_COUNT=0
SKIP_COUNT=0

echo "$VIP_MAP" | python3 -c "
import json, sys
items = json.load(sys.stdin)
for item in items:
    if item.get('forti_vip') and item.get('avi_vip'):
        print(f\"{item['avi_vip']}|{item['forti_vip']}|{item['vs_name']}\")
" | while IFS='|' read -r AVI_VIP FORTI_VIP VS_NAME; do
    # Find DNS records for this AVI VIP
    REFS=$(echo "$DNS_RECORDS" | python3 -c "
import json, sys
records = json.load(sys.stdin)
refs = [(r['_ref'], r['name']) for r in records if r.get('ipv4addr') == '$AVI_VIP']
for ref, name in refs:
    print(f'{ref}|||{name}')
" 2>/dev/null)

    if [[ -z "$REFS" ]]; then
        info "No DNS record found for AVI VIP $AVI_VIP (VS: $VS_NAME) — skipping"
        SKIP_COUNT=$((SKIP_COUNT + 1))
        continue
    fi

    while IFS='|||' read -r REF HOSTNAME; do
        if $DRY_RUN; then
            echo "  [DRY-RUN] Would update: $HOSTNAME  $AVI_VIP → $FORTI_VIP"
        else
            RESULT=$(curl -sk -X PUT \
                -u "${INFOBLOX_USER}:${INFOBLOX_PASS}" \
                -H "Content-Type: application/json" \
                -d "{\"ipv4addr\": \"$FORTI_VIP\"}" \
                "${WAPI_BASE}/${REF}" 2>/dev/null || echo "ERROR")

            if echo "$RESULT" | grep -q "record:a/"; then
                ok "Updated: $HOSTNAME  $AVI_VIP → $FORTI_VIP"
                CHANGE_COUNT=$((CHANGE_COUNT + 1))
                echo "$(date -u '+%Y-%m-%dT%H:%M:%SZ') CHANGED $HOSTNAME $AVI_VIP → $FORTI_VIP" \
                    >> "$LOG_DIR/${ENV}-dns-changes.log"
            else
                fail "Failed to update: $HOSTNAME — $RESULT"
            fi
        fi
    done <<< "$REFS"
done

ok "Phase 2 complete"

# ── Phase 3: Verify ───────────────────────────────────────────────────────────
step "Phase 3: Verification"

if $DRY_RUN; then
    info "[DRY-RUN] Would verify all updated records resolve to FortiADC VIPs"
else
    info "Verifying updated records..."
    VERIFY_PASS=0; VERIFY_FAIL=0

    echo "$VIP_MAP" | python3 -c "
import json, sys
items = json.load(sys.stdin)
for item in items:
    if item.get('forti_vip') and item.get('avi_vip'):
        print(f\"{item['forti_vip']}\")
" | sort -u | while read -r EXPECTED_VIP; do
        # Brief propagation wait
        sleep 2
        # Verify via Infoblox API (authoritative — not DNS resolver)
        ACTUAL=$(curl -sk -u "${INFOBLOX_USER}:${INFOBLOX_PASS}" \
            "${WAPI_BASE}/record:a?ipv4addr=${EXPECTED_VIP}&view=${INFOBLOX_VIEW}&_return_fields=name,ipv4addr" \
            2>/dev/null | python3 -c "
import json, sys
d = json.load(sys.stdin)
if d:
    print(d[0].get('ipv4addr', 'NOT_FOUND'))
else:
    print('NOT_FOUND')
" 2>/dev/null || echo "ERROR")

        if [[ "$ACTUAL" == "$EXPECTED_VIP" ]]; then
            ok "Verified: $EXPECTED_VIP → FortiADC"
            VERIFY_PASS=$((VERIFY_PASS + 1))
        else
            fail "Verify failed: expected $EXPECTED_VIP, found $ACTUAL"
            VERIFY_FAIL=$((VERIFY_FAIL + 1))
        fi
    done

    if [[ "$VERIFY_FAIL" -gt 0 ]]; then
        fail "$VERIFY_FAIL record(s) failed verification."
        warn "Consider rollback: bash scripts/rollback.sh --env $ENV --execute"
        exit 1
    fi
    ok "All records verified successfully"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  DNS Cutover ${MODE} — COMPLETE"
echo "  Environment : $ENV"
echo "  Finished    : $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
if $DRY_RUN; then
echo "  Result      : DRY-RUN complete — no real changes made"
echo "  Next step   : Run with --execute to apply real changes"
else
echo "  Result      : DNS records updated. Traffic routing to FortiADC."
echo "  Backup      : $BACKUP_FILE"
echo "  Changes log : $LOG_DIR/${ENV}-dns-changes.log"
echo "  Rollback    : bash scripts/rollback.sh --env $ENV --execute"
fi
echo "══════════════════════════════════════════════════════════════"
echo ""

if ! $DRY_RUN; then
    echo "POST-CUTOVER ACTIONS:"
    echo "  1. Monitor FortiADC VS health for 30 minutes"
    echo "  2. Confirm application teams see no errors"
    echo "  3. Check FortiADC access logs for traffic"
    echo "  4. AVI remains live as fallback — do NOT decommission yet"
    echo "  5. After 24h clean: schedule AVI decommission"
    echo ""
fi
